### ISSUE TITLE
Frequent badge errors

### ISSUE THREAD

**Issue by shawnps** [vieux/gocover.io#27]
Hello, I frequently see "error" as the status of our coverage badge here:

http://github.com/client9/ipcat

Any thoughts on how to fix?

**Comment by empijei** [comment]
Hi all, my two cents on this issue,
[this  github issue](https://github.com/github/markup/issues/224) is one of the responsible for this error (which I am getting on my [wapty project](https://github.com/empijei/wapty/issues/9)).

But the problem here is that to prevent github from caching the content the image should have the header `Expires`, `Last-Modified` or `Etag` set. That **would likely fix the issue** as it is the suggested solution.

If it still does not work it could be due to the redirection that gocover.io performs to img.shields.io as shown below:
```sh
curl -i 'https://gocover.io/_badge/github.com/empijei/wapty?nocache=wapty'
```
```http
HTTP/1.1 302 Found
Date: Mon, 02 Oct 2017 14:02:26 GMT
Server: Apache/2.4.18 (Ubuntu)
Cache-Control: no-cache
Location: https://img.shields.io/badge/coverage-65.0%25-green.svg?style=flat
Content-Length: 89
Content-Type: text/html; charset=utf-8

<a href="https://img.shields.io/badge/coverage-65.0%25-green.svg?style=flat">Found</a>.
```

which, itself, has a cache-control max-age set to 86400 seconds (1 day). 
```http
HTTP/2 200 
date: Mon, 02 Oct 2017 14:03:00 GMT
content-type: image/svg+xml;charset=utf-8
set-cookie: __cfduid=d6e3c4792c3d74412e8a626f02a51b8441506952979; expires=Tue, 02-Oct-18 14:02:59 GMT; path=/; domain=.shields.io; HttpOnly
cache-control: max-age=86400
last-modified: Mon, 02 Oct 2017 13:24:42 GMT
server: cloudflare-nginx
cf-ray: 3a7833da7e7e2780-FRA

[...]
```
If this is the case it is github fault that uses the cache of a 302 redirect instead of the cache of the source image.

(only 301 responses should use the destination cache)
